title: Bhavesh Vaghela 

author:
  name: Bhavesh Vaghela
  #email: your-email@domain.com
description: #> # this means to ignore newlines until "show_excerpts:"
  Welcome to my world

footer: All rights reserved 


google_analytics: G-NGHJ6G0CLQ

disqus:
    shortname: vaghelabhavesh-github-io

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  social_links:
    devto: vaghelabhavesh
    github:  vaghelabhavesh
    linkedin: vaghelabhavesh
    twitter: vaghelabhavesh

header_pages:
 - about.md
 # cv.md
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
